### PR TITLE
Add Searchbar Component

### LINKED ISSUE #136: [FEATURE] Search Bar Component
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to add search bar component in the components page. The search bar component allows users to search for content or products within the website.

### Proposed Solution

I will add the search bar component aligning with the other glassmorphic components and the purpose of the website.

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

_No response_

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #136 

Added the searhbar card in GlassyUIComponents page and Searchbar component on the /searchbar-details route .

https://github.com/user-attachments/assets/a01c8fdb-5f6d-4252-bf4d-03bb4ed29092

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@haseebzaki-07, some checks are not passed can you please take a look.

**Comment by haseebzaki-07** [comment]
@Jaishree2310 The deploy preview failed again, Please help out , I looked on my side and tried to resolve

**Comment by Jaishree2310** [comment]
@haseebzaki-07 Please ask other contributors to help you so that you can connect more people in open source.

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah ^
Please help him with this issue to resolve.

**Comment by haseebzaki-07** [comment]
@Jaishree2310 sure I appreciate getting help from fellow contributors but this time I think there is some issue specific to this project, I see almost every PRs facing this issue in you repo.

**Pull request merged**
