### PR TITLE
Want to improve color grading of the components page. #32

### PR DESCRIPTION
**Pull request by Mr-DK07**
Hey @Jaishree2310  Color grading of component page has updated. Just check, and let me know, anything else you want.

Screenshot 2024-10-06 115956

Don't forget to assign labels (gssoc-ext , hactoberfest and Level1, Level2, Level3) before merge.

### CODE REVIEW

**Review by Jaishree2310 — DISMISSED** [review]
Done

**Review by Jaishree2310 — COMMENTED** [review]
Please check all the comments and whitespaces

**Comment by Mr-DK07** [comment]
okay

**Comment by Mr-DK07** [comment]
check this now

**Comment by Jaishree2310** [comment]
@Mr-DK07 Please rebase the PR to resolve the merge conflict.

**Pull request closed without merging**
