### PR TITLE
feat: Added Social Media Icons Switch Component for GlassyUI #20

### PR DESCRIPTION
**Pull request by masabinhok**
**Title:** Add Speed Dial Component for Social Media Icons

**Description:**

Hi Team,

I’ve successfully created a Speed Dial component for the Glass UI component library, featuring various social media icons for quick access. 

### Overview:
- The Speed Dial component allows users to quickly navigate to their favorite social media platforms.
- Icons included: Facebook, Twitter, Instagram, and more.

### Changes Made:
- Implemented the Speed Dial component.
- Ensured responsiveness and accessibility.

### Testing:
- Verified functionality across different devices.
- Checked keyboard navigation for accessibility compliance.

https://github.com/user-attachments/assets/e0a4e34b-c7f3-4172-9e3e-dfcbcb511c58

I welcome any feedback or suggestions for improvements. Looking forward to your reviews!

### CODE REVIEW

**Comment by masabinhok** [comment]
I doubt if its working properly; my build version is completely fine.

**Comment by masabinhok** [comment]
You can merge this PR, and try to fix this netlify automated check issue once.

**Comment by Jaishree2310** [comment]
@masabinhok, it looks good but can you please use the same method for other components ... such as props, basic usage, customizable elements, and small and meaningful code to copy not the whole code.

**Comment by masabinhok** [comment]
I have done accordingly, but i bet these code would not run on copy paste without the original component code.

**Review by Jaishree2310 — APPROVED** [review]
Done

**Comment by rajesh-puripanda** [comment]
Badge component — notification badges, status indicators, count badges. Colored variants with glass backdrop. @Jaishree2310 please assign.

**Pull request merged**
