### PR TITLE
Added glassmorphism theme in donate page

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have added glassmorphism theme in donation page

image

Issue #303

### CODE REVIEW

**Comment by Gauravtb2253** [comment]
Hello Pls add level label to the PR

**Comment by Gauravtb2253** [comment]
Hello

**Comment by AKSHITHA-CHILUKA** [comment]
@Jaishree2310 add gssoc-ext and level labels

**Comment by Gauravtb2253** [comment]
@Jaishree2310 any updates

**Pull request merged**
