### PR TITLE
Added animation !!

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #282

https://github.com/user-attachments/assets/c169a18c-29b4-411c-a281-8559c06dc996

Added beautiful animation on scrolling and rendering of the page 
Added animation on contributor page too
Now website look more smooth 
it will enhance the user experience 
Note : before using it do "npm i"  once

in any case you want changes comment down i will do it !!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Please check i have removed conflicts!!

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 its a kind request please merge this PR now , so that i can effectively work on next issue else again it crease merge conflicts please

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 done resolving conflicts

**Pull request merged**
