### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neeru24**
Added table metrices to the readme that will be UPDATED AUTOMATICALLY.

Kindly merge it @Jaishree2310 . 
fixes: #222 

Thank you!!

image

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@neeru24 Deployment has failed please check

**Comment by Jaishree2310** [comment]
@neeru24 Let me solve the conflict.

**Comment by neeru24** [comment]
> @neeru24 Let me solve the conflict.

Hi @Jaishree2310 
I'm not assigned with the labels.. Kindly assign me for this PR. It's not getting counted towards the leaderboard.

image

**Comment by MastanSayyad** [comment]
@Jaishree2310 add labels

**Pull request merged**
