### PR TITLE
Survey form

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello

I have added the survey form to the website

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Gauravtb2253 Please resolve the conflicts.

**Comment by Gauravtb2253** [comment]
any updates

**Comment by Gauravtb2253** [comment]
hello any updates on this

**Comment by Gauravtb2253** [comment]
Issue #304

**Comment by Gauravtb2253** [comment]
Hello Pls add level label to the PR

**Comment by Gauravtb2253** [comment]
Hello

**Comment by AKSHITHA-CHILUKA** [comment]
@Jaishree2310 add gssoc-ext and level labels

**Pull request merged**
