### PR TITLE
changed in the UI

### PR DESCRIPTION
**Pull request by shruti9935**

### CODE REVIEW

**Comment by shruti9935** [comment]
@Jaishree2310 i didnt got rewards of this pr can you tell me how much time its gonna take coz tomorrow is last date

**Comment by shruti9935** [comment]
@Jaishree2310 i didnt received the points can you check from your side why is it so

**Comment by aslams2020** [comment]
@Jaishree2310 Please Add the `gssoc-ext` and `level` tags to this PR. The Contributor @shruti9935 Didn't get the points for it.

Best regards, 
Aslam Sayyad
Core Team GSSoC Extd.

**Comment by shruti9935** [comment]
I didnt got my points its been 10 days

**Pull request merged**
