### PR TITLE
Added product page card for ecommerce website

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #220 

Screenshot 2024-10-18 005006

Screenshot 2024-10-18 004948

Created a beautiful product info showing card which can be suits on any ecommerce website a very useful UI for developer !!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah where is the glassmorphism theme ?

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah One thing I have noticed making just PR won't help you but making valuable changes and maintaining the order of components by taking examples from the component-like button will help you more.

**Comment by Sawan-Kushwah** [comment]
image


image

@Jaishree2310 Now its better as i seperated svgs from the code so that it should not look length and given that SVG's in another block
Also uses glassmorphism class 
Given props accordingly 
customization of card can be given but it make code too big !! and i think its not feasible in big components but if you wish i can do it !!
else i have done necessary changes as mention in Redme.md 
if something missing then let me know i will improve it !!

**Comment by Jaishree2310** [comment]
Please resolve the conflicts and add props.

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/e36d418b-e628-45e4-bb1a-1d841928a257

@Jaishree2310 Please watch this ! i have given 
basic usage 
svg used 
props
example

in sequence

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Conflicts resolved !

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah still the conflict is present

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 done!!

**Pull request merged**
