### PR TITLE
Adding a About us page

### PR DESCRIPTION
**Pull request by hritika2409**
https://github.com/user-attachments/assets/029ba8db-6293-4eaf-9f35-da26b3daf7ee

Added and updated the AboutUs page to more responsive and interactive way and more similar to the website

my issue number is
Adding a About us page #131

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@hritika2409, social media icons are there are they even redirecting?
If not then use only github for project

**Comment by hritika2409** [comment]
ok sure @Jaishree2310

**Comment by hritika2409** [comment]
Yes they were redirecting but to the login page @Jaishree2310

**Comment by hritika2409** [comment]
Updated the icons 

https://github.com/user-attachments/assets/1f8f3843-02ab-4288-a26f-d6d9143ef731

Now they are working like this

**Comment by Jaishree2310** [comment]
@hritika2409 Please resolve the conflicts

**Comment by hritika2409** [comment]
@Jaishree2310 Its do ,Is it fine now?

**Comment by hritika2409** [comment]
@Jaishree2310 please change you remove that from your end as i saw everyone if facing the same issue

**Pull request merged**
