### PR TITLE
Added the Contributors page super amazing and professional.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the Contributors page super amazing and professional.

closes- #86 

Demo video :- 

https://github.com/user-attachments/assets/987402e0-a253-4633-98f3-b2264fdf7889

@Jaishree2310 Check this PR and merge it and assign this to me and put relevent labels like gssoc 2024 ext, hacktoberfest and level, i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@tarunkumar2005 Please resolve the conflicts.

**Comment by tarunkumar2005** [comment]
Okay i am quickly solving the issue but are you just putting it level 1 ??

**Comment by tarunkumar2005** [comment]
@Jaishree2310 Now check issues resolved.

**Comment by tarunkumar2005** [comment]
@Jaishree2310 Check now there are no issues in the PR

**Comment by tarunkumar2005** [comment]
@Jaishree2310 Please check it now there are no conflicts now i have solved the issues.

**Comment by tarunkumar2005** [comment]
@Jaishree2310 Check the PR now ??

**Comment by tarunkumar2005** [comment]
@Jaishree2310 Still it is pending for review can you check this and merge it.

**Comment by tarunkumar2005** [comment]
@Jaishree2310 It can be level 3 as the ui design it so good and it is responsive for all screen sizes so i have done complete work on the page so it can be level 3

**Pull request merged**
