### PR TITLE
Light / Dark theme toggle button

### PR DESCRIPTION
**Pull request by coderashhar**
Added a button which switches between light and dark mode.

Closes issue #14 

The dark mode styles remain as it is and I have added light theme styles, Here are some screenshots.

Home Page
Screenshot 2024-10-28 at 12 09 18 PM

Toggle Button 
Screenshot 2024-10-28 at 12 11 31 PM

Components Page
Screenshot 2024-10-28 at 12 12 35 PM

Component Details Page
Screenshot 2024-10-28 at 12 13 27 PM
Screenshot 2024-10-28 at 12 14 16 PM

Contributors Page
Screenshot 2024-10-28 at 12 15 38 PM

Donation Page
Screenshot 2024-10-28 at 12 16 05 PM

### CODE REVIEW

**Comment by coderashhar** [comment]
@Jaishree2310 Kindly review and merge my PR

**Comment by coderashhar** [comment]
@Jaishree2310 kindly review it

**Comment by Jaishree2310** [comment]
@coderashhar Please resolve the conflicts.

**Comment by coderashhar** [comment]
@Jaishree2310 I have resolved the merge conflicts , kindly merge my PR

**Comment by Jaishree2310** [comment]
@coderashhar Issue is still present as you can see the conflicts. Once you resolved all i will merge the PR. Thank you!

**Comment by coderashhar** [comment]
@Jaishree2310 kindly merge asap as other people are also contributing new conflicts keep arising.

**Comment by coderashhar** [comment]
@Jaishree2310 i have resolved conflicts kindly merge my PR.

**Comment by coderashhar** [comment]
@Jaishree2310 please respond

**Pull request merged**
