### PR TITLE
Replace default React favicon with a custom Icon

### PR DESCRIPTION
**Pull request by kodurisaivishnu**
I have created a custom logo for the GlassyUI-Components. This feature will enhance the UI and provide a more visually appealing appearance.

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@kodurisaivishnu, Please resolve the conflicts.

**Comment by kodurisaivishnu** [comment]
ok mam the confilcts are resolved
image
and the logo is perfectly  showing 
image

**Comment by Jaishree2310** [comment]
@kodurisaivishnu, Please rebase the PR to resolve the merge conflict.

**Comment by kodurisaivishnu** [comment]
code rebase sucess!

**Comment by kodurisaivishnu** [comment]
but why it is failing in deployment preview what might be the reason

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah, Can you help him with this issue.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 try to revert the changes of this PR
And delete this one as it is not a big issue so we can revert this and ask him to delete the fork of code and refork it then clone it and then do the necessary changes then again make PR

**Pull request closed without merging**
