### PR TITLE
added scroll to top button

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have added the scroll to top button in about and contributors page
pls check

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Gauravtb2253 Please always check to resolve the conflicts.

**Comment by Gauravtb2253** [comment]
pls check

**Comment by Jaishree2310** [comment]
@Gauravtb2253, Why are all checks not passing?

**Comment by Gauravtb2253** [comment]
should I create new PR

**Pull request merged**
