### PR TITLE
Implemented contact form with frontend and Backend API

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue : #405 

https://github.com/user-attachments/assets/02a65e79-11a8-4106-9128-e39d5c6836fb

i have added send mail feature to contact form for instant resolving the user querry

in the formated way you will get mail to your mail account
clean and clear UI of mail

fill this env.example info for using this mail feature

admin mail where you want to send the user info
mail by this mail you will receive mail
passkey you have to generate one from
application password on mail !!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah See the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 done resolving conflicts !!

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Can i get level 3 for it ? As i have implemented full backend and mail feature

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 you can review my code !! proper folder structure for backend and efficient api handling

**Pull request merged**
