### PR TITLE
Fixes all the issues in rendering

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
https://github.com/user-attachments/assets/ef682e0c-dda0-4e66-ad21-f528c67ce53e

### CODE REVIEW

**Comment by Jaishree2310** [comment]
let see if this helps

**Comment by Jaishree2310** [comment]
image

its showing error

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah ^

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 okay let me see

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 meanwhile try to run it locally

**Comment by Sawan-Kushwah** [comment]
in my local it is working as smooth as before !!
may be you can redeploy on the vercel !!

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 does it works ??

**Comment by Jaishree2310** [comment]
> in my local it is working as smooth as before !! may be you can redeploy on the vercel !!

I did this it went for all the checks and then failed.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 in vercel?

> > in my local it is working as smooth as before !! may be you can redeploy on the vercel !!
> 
> I did this it went for all the checks and then failed.

**Comment by Sawan-Kushwah** [comment]
What checks got failed?

**Pull request merged**
