### PR TITLE
Added pricing page component

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #79 

Done pricing page 
added code for pricing page components

also given prop for it 

and given some example 

Screenshot 2024-10-11 185045

Screenshot 2024-10-11 185101

Screenshot 2024-10-11 185113

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah, Please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 i think its because i have push all components at once 
no worries i have resolved all the conflits of all 3  pull request if still some problem i will resolved it !!

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 i have resolved conflicts !!

**Pull request merged**
