### PR TITLE
added calendar component

### PR DESCRIPTION
**Pull request by gurliv21**
https://github.com/user-attachments/assets/06f5c2ca-3c82-4d80-a43c-86dc7b0a9c7c

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@gurliv21 Please resolve the conflicts.

**Comment by gurliv21** [comment]
conflicts resolved

**Comment by Jaishree2310** [comment]
@gurliv21 resolve the conflicts

**Comment by gurliv21** [comment]
@Jaishree2310 conflict resolved

**Comment by Jaishree2310** [comment]
@gurliv21 Please resolve the conflicts!

**Comment by gurliv21** [comment]
@Jaishree2310 conflict resolved

**Pull request merged**
