### PR TITLE
added cursor-animation

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Jaishree2310 
i have added cursor animation

https://github.com/user-attachments/assets/31c89534-0b79-45be-99c9-3e3e883cb7a8

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@AswaniBolisetti, Please resolve the conflicts.

**Comment by Jaishree2310** [comment]
@AswaniBolisetti, Please rebase the PR to resolve the merge conflict.

**Comment by Jaishree2310** [comment]
@AswaniBolisetti, Please resolve the conflicts. Check again

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 could you please tell me how to do these, actually I tried but I was confused with resolving conflicts

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 could you please merge this, dont delete please accept it

**Comment by omkumar312** [comment]
I want to work on this issue.

**Comment by Jaishree2310** [comment]
> @Jaishree2310 could you please merge this, dont delete please accept it

Could you get help from other contributors?
@AswaniBolisetti This will help you to understand better how to engage with others.

**Comment by Jaishree2310** [comment]
@omkumar312 If you can help her.

**Review by Jaishree2310 — APPROVED** [review]

**Comment by Jaishree2310** [comment]
> @Jaishree2310 i resolved the conflicts kindly check it out

Deployment is failed.

**Pull request merged**
