### PR TITLE
added scroll progress bar

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Jaishree2310 
I have created scroll progress bar successfully
Kindly look at it

https://github.com/user-attachments/assets/5eaa8fc8-fc73-4171-a6d3-7091f51c40ed

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 could you please review it

**Comment by Jaishree2310** [comment]
@AswaniBolisetti Please always check to resolve the conflicts.

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 I resolved the conflicts before, I dont know why they raised again, now i resolved again kindly check it out

**Comment by Jaishree2310** [comment]
@AswaniBolisetti No it's not resolved it is creating still conflicts.

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Could you please check now, resolved the conflicts

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 could you please review it

**Comment by Jaishree2310** [comment]
@AswaniBolisetti Thank you for your contribution.

**Pull request merged**
