### PR TITLE
Added gallery component

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #218 

image

 
Screenshot 2024-10-17 200904

created a beautiful gallery components

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah No its not looking good, i am sure you can enhance this more.
Also the basic usage code why it is so big and there is no customization props, etc 
Please check the order of component given in the read me

**Comment by Sawan-Kushwah** [comment]
image

image

@Jaishree2310 Added hover effect , glassmorphism class , and make the code more modulaar , seperated Images and put in array , also combined common classes in one variable and if extra classes need that can be passed in extra class variable , also added props for customization!!

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310  okay please wait 5 min

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 
https://github.com/user-attachments/assets/8f6b9f9a-ac09-408b-953d-855e0ea57e81

I have added everything in sequence in code

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 done!

**Pull request merged**
