### PR TITLE
#Issue21 Adding animation/transition to main in Components Page and centering text above boxes

### LINKED ISSUE #21: Feature Request: Adding transitions to some text
I'd like to work on adding fade transitions to some of the text for a smoother experience. I may also adjust the alignment for "Glassmorphic Components". I'd like to be assigned to work on this for my first contribution for gssoc.

### PR DESCRIPTION
**Pull request by NazTM**
Closes #21

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@NazTM, Please resolve the conflicts.

**Comment by NazTM** [comment]
Conflicts resolved, had to remove website preview from readme.md because of on-going changes to the website. Do all the deploy previews need to pass?
@Jaishree2310

**Comment by Jaishree2310** [comment]
> Conflicts resolved, had to remove website preview from readme.md because of on-going changes to the website. Do all the deploy previews need to pass? @Jaishree2310 apologies for any misunderstanding, am new to all of this

Please rebase the PR to resolve the merge conflict.

**Comment by NazTM** [comment]
@Jaishree2310 did that, is it resolved now?

**Comment by Jaishree2310** [comment]
> @Jaishree2310 did that, is it resolved now?

No its not resolved please check again.

**Comment by Jaishree2310** [comment]
@NazTM, you can ask to help you to other contributors. This makes doubts clearer and helps the conflicts to be resolved properly.

**Comment by mehul-m-prajapati** [comment]
You need to rebase your changes with upstream

**Comment by NazTM** [comment]
@Jaishree2310 how about now?

**Pull request merged**
