### PR TITLE
Removed all issues

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
Screenshot 2024-11-07 144932

https://github.com/user-attachments/assets/29ee314e-0bb1-4427-9d6c-a378fed4bc20

i have remove all the issue but then too it is showing some unexpected error
page is not rendering properly and components doesn't get scroll

i also have older version of glassui 
if you want i can make PR of that tooo

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 will i get some level tag for this PR ?
just asking

**Comment by Jaishree2310** [comment]
can you do something
so that the website can look better again

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 i can raise a PR where i have older version of this if you merge that PR then some of new features may get removed but our website will work smoothly

**Comment by Sawan-Kushwah** [comment]
As before

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 if you say i can do it

**Comment by Jaishree2310** [comment]
Yes raise that PR I will merge that

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 please be active i am rasing pr right now

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Done?

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 yes i have created PR #425

**Pull request merged**
