### PR TITLE
added Navigation component basic usage

### PR DESCRIPTION
**Pull request by IshuSinghSE**
I have fix the following in this PR and it 

- [x]  Closes: #240 
- [x]  Closes: #275 
- [x] fixed Typo in ToastPage Closes: #330 
- [x] fixed error for setfilteredData in GlassyUIComponents to data 
- [x] formatted Speedial example code
- [x] fixed props default for  textarea components

Feel free to tell me about any changes required!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@IshuSinghSE Please resolve the conflicts.

**Comment by IshuSinghSE** [comment]
> @IshuSinghSE Please resolve the conflicts.

Could you just suggest me that, how can I resolve the conflicts? I tried, but unable to resolve
.

**Comment by Jaishree2310** [comment]
@IshuSinghSE Please resolve the conflicts!

**Comment by IshuSinghSE** [comment]
> This branch has no conflicts with the base branch

Now I have resolved all the conflicts, please let me know for any changes!

**Comment by IshuSinghSE** [comment]
> Now I have resolved all the conflicts, please let me know for any changes!

Now I have resolved all the conflicts, please let me know for any changes!

**Comment by Jaishree2310** [comment]
@IshuSinghSE Please resolve the conflicts.

**Pull request closed without merging**
