### PR TITLE
#9  Add : Glassmorphic Tooltip Component to GlassyUI

### PR DESCRIPTION
**Pull request by kodeCraze**
Introducing a new Tooltip component to the GlassyUI library, implementing a glassmorphism theme.

## Features

- Displays helpful information on hover
- Customizable text content
- Multiple position options (top, bottom, left, right)
- Glassmorphism styling (transparency, blur effect, frosted glass look)
- Responsive design

## Implementation Changes Details.

1. `GlassyUIComponentsPage.tsx`
2. `App.tsx`
3. `TooltipDetailsPage.tsx`
4. `Tooltip.tsx` 

## Screenshots

(Screenshot : 1)

Screenshot 2024-08-05 160303

(Screenshot : 2)

Screenshot 2024-08-05 160356

## Checklist

- [+] Component code implemented
- [+] Styling adheres to glassmorphism theme
- [+] Responsive design tested
- [+] Code follows project style guidelines
- [+] Support different positions (top, bottom, left, right).

### CODE REVIEW

**Comment by Jaishree2310** [comment]
Hey @kodeCraze , thank you for completeing the issue. Would like you to make some changes such as the small error in the text part and text color. Take look and correct small changes. 
Tooltip on left is not visible with white font with the background as seen in the shared pic.
Screenshot (351)
Screenshot (350)

**Comment by kodeCraze** [comment]
Greetings @Jaishree2310,

Thank you for taking the time to review my code. I appreciate your valuable feedback and the suggestions you've shared. I will carefully consider your recommendations and work on implementing the proposed improvements.

**Comment by Jaishree2310** [comment]
> @Jaishree2310 so, i have changed the text color, also tried a new thing, should i keep both the code or should i keep one ? is there any suggestions.
> 
> Screenshot : 01
> 
> Screenshot 2024-08-08 011032
> 
> Screenshot : 02
> 
> Screenshot 2024-08-08 011138

I think 1st pic looks good because the icons do not match what we want the user to understand.

**Review by Jaishree2310 — COMMENTED** [review]
you can remove the extra spaces and the comments which are no longer require

**Comment by Jaishree2310** [comment]
@kodeCraze, I've attached a few pictures that need review. Please ensure that the code is adjusted so the elements don't overlap with other sections or extend beyond the page boundaries. It's important to avoid these issues to maintain a professional presentation of the project.

Screenshot (355)
Screenshot (356)
Screenshot (353)
Screenshot (354)

**Comment by Jaishree2310** [comment]
@kodeCraze, Any update on this?

**Comment by kodeCraze** [comment]
> @kodeCraze, Any update on this?

I'am Working on it.

**Comment by kodeCraze** [comment]
Checkout this @Jaishree2310 

URL 1 : https://glowing-space-lamp-4j74jg44j46rfq965-3000.app.github.dev/components

URL 2 : https://glowing-space-lamp-4j74jg44j46rfq965-3000.app.github.dev/tooltip-details

**Comment by kodeCraze** [comment]
Hello @Jaishree2310,

I've submitted a pull request (#9) to add a Glassmorphic Tooltip Component to GlassyUI. I'm excited about contributing to this project and would appreciate your review.
Could you please take a look at my changes when you have a moment? I'm particularly interested in any feedback on:

Code quality and style - Does it align with the project's standards?
Component functionality - Are there any features missing or improvements needed?

I'm open to any suggestions for improvement and happy to make any necessary changes. If there's anything else I should do to help get this PR ready for merging, please let me know.

Thank you for your time and for considering my contribution!
Best regards,

@kodeCraze

**Comment by Jaishree2310** [comment]
Hey @kodeCraze, It's looking good. But Inside it shows a 404 error page which should not be the case in the components because the main purpose is to help other developers use it effectively and with customized components.

**Comment by kodeCraze** [comment]
> Hey @kodeCraze, It's looking good. But Inside it shows a 404 error page which should not be the case in the components because the main purpose is to help other developers use it effectively and with customized components.

Hi @Jaishree2310 , thanks for the feedback! Could you please share a screenshot or the specific steps that lead to the 404 error? This will help me identify the issue more effectively and ensure the components are working as intended. Appreciate your help!

**Comment by Jaishree2310** [comment]
@kodeCraze I have merged the PR. 
Thank you for your contribution!!

**Pull request merged**
