### PR TITLE
Corrected the order of Modal component

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #237 

 

https://github.com/user-attachments/assets/3841b417-1999-43a1-8967-e39b9a65548f

Added required mention in #237 !!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Resolve the conflicts

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Done Resolving all the conflicts

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 please Review and merge my PR so that i can work on next issue otherwise it will again  create merge conflicts

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts!

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Review by Jaishree2310 — APPROVED** [review]

**Pull request merged**
