### PR TITLE
Added contact us page

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #118 

https://github.com/user-attachments/assets/77de708f-a1e5-4219-95e5-4ee581831ed5

Screenshot 2024-10-14 195433

Added theme oriented contact page
on submit it handle the submit and show the data on console so in future it get easy to integrate with backend

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah, Where this message is being received?

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 for now this is on console we can integrate backend for it or we can use mail facility by web3

**Comment by Jaishree2310** [comment]
> @Jaishree2310 for now this is on console we can integrate backend for it or we can use mail facility by web3 it required owner mail and some info that's why i didn't integrated it

If we are not receiving any queries then we should not implement such a feature.
If anything else you want, you can add which will not give the wrong direction to the user.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 can i give it as a component ? Named as contact us form !?

**Comment by Jaishree2310** [comment]
> @Jaishree2310 can i give it as a component ? Named as contact us form !? then people can easily integrate there backend with using this form ? is this is okay to you i will update my code and update you!!

okay

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 
issue #141 
Screenshot 2024-10-16 215603

Screenshot 2024-10-16 215623


Screenshot 2024-10-16 215637



I have given the contact form as a component 
Give UI part of form 
Also given a working contact form example 
Frontend part logic part of contact form is also given 

Fully customizable contact form is given

**Pull request merged**
