### PR TITLE
Resolve all the dark mode issues in rendering

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue : #427 

https://github.com/user-attachments/assets/ef682e0c-dda0-4e66-ad21-f528c67ce53e

done resolving issues 

Please check it onces
Now it will definitely works as before !!
i have that dark mode from everywhere

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 please tell does it works?

**Comment by Jaishree2310** [comment]
It worked so good!
Thank you for your support and all😊👍

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Now can i work on other issues !!

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 one more thing don't merge old PR's other wise people in solving conflicts can create problem !!
merge only latest PR !

**Pull request merged**
