### PR TITLE
Resolved pr #250 conflict for issue #197 

### PR DESCRIPTION
**Pull request by BaraniVA**
This pull request is created to resolve the conflicts arose in the tabs branch for pr #250 and conflict for issue #197

### CODE REVIEW

**Comment by BaraniVA** [comment]
Hi @Jaishree2310 I'm really sorry for the troubles caused i have resolved the conflicts now but I'm not sure why it kept getting conflicts.

**Comment by Jaishree2310** [comment]
@BaraniVA resolve the conflicts

**Comment by Jaishree2310** [comment]
@BaraniVA Please resolve the conflicts!

**Comment by Jaishree2310** [comment]
@BaraniVA Please resolve the conflicts.

**Comment by BaraniVA** [comment]
@Jaishree2310 resolved the conflicts please check and let me know for further issues and changes

**Comment by BaraniVA** [comment]
@Jaishree2310 sorry about the conflicts and issues hope you like my work also thank you for merging my pr

**Comment by BaraniVA** [comment]
Hi @Jaishree2310, kindly add labels to this PR when you get a chance. Thanks!

**Comment by BaraniVA** [comment]
@Jaishree2310 it seems like the tabs component isnt added with the rest of the components on the page is there any problem? i can work on it if there exists any conflict. please look into it and let me know about any issue.

**Pull request merged**
