### PR TITLE
Add Checkbox Glassy Component

### LINKED ISSUE #188: [FEATURE]: Add Checkbox
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to add Checkbox for glassyUI components.
Description: Allows users to select multiple options from a list.
Use Case: Forms, settings, filters.

### Proposed Solution

I will add a checkbox generating codes and glassyUI classes.

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

I will create a page in react that will contain the codes for creating a checkbox glassy component.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #188 

This PR adds glassy checkbox component to the glassy components page and is available at the /checkbox route.

The application was breaking , I also fixed it.

Screenshot 2024-10-17 115546
Screenshot 2024-10-17 123025
Screenshot 2024-10-17 123040
Screenshot 2024-10-17 123458

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@haseebzaki-07 Please always check to resolve the conflicts.

**Comment by haseebzaki-07** [comment]
hey @Jaishree2310 resolved the conflicts

**Comment by haseebzaki-07** [comment]
hey @Jaishree2310 can you please explain what I am expected to do, I am not getting.

**Comment by haseebzaki-07** [comment]
hey @Jaishree2310 please check this

**Comment by Jaishree2310** [comment]
@haseebzaki-07 Well done! Thank you for your contribution.

**Comment by Jaishree2310** [comment]
@haseebzaki-07 Please resolve the conflicts.

**Comment by haseebzaki-07** [comment]
@Jaishree2310 resolved conflicts

**Comment by haseebzaki-07** [comment]
hey @Jaishree2310 please merge this PR

**Pull request merged**
