### PR TITLE
Corrected the order of speed dial component

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #235 

https://github.com/user-attachments/assets/d45164d0-daa4-42b6-b4a1-6040aa4424b7

Added the customizable speed dial component ! 
Current order of speed dial !
Basic usage 
props
customizable 
code 
example

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah, Please resolve the conflicts.

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Resolved conflicts !! please review and merge if it again create conflicts i will solve instantly

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 done resolving conflicts !!

**Pull request merged**
