### PR TITLE
Added Tabs feature for issue #197

### PR DESCRIPTION
**Pull request by BaraniVA**
### PR for issue no #197 

**Description:**
This pull request introduces a new Tabs component to the GlassyUI-Components library. The Tabs component allows users to create tabbed interfaces with a glassmorphic design, consistent with the existing theme of the project.

**Changes:**

**New Files:**
**Tabs.tsx:** Defines the Tabs and Tab components.
**TabsDetail.tsx:** Provides an example usage of the Tabs component.

**Updated Files:**
**GlassyUIcomponentspage:** Added a new ComponentCard for the Tabs component, displaying it on the components page.

**Implementation Details:**
The Tabs component manages the state of the active tab and renders the content of the selected tab.
The **TabsDetail.tsx** file demonstrates how to use the Tabs component with multiple tabs.
The **GlassyUIComponentsPage.tsx** file has been updated to include a new card for the Tabs component, ensuring it is displayed alongside other components.

**Screenshot**

image
image

### CODE REVIEW

**Comment by BaraniVA** [comment]
Hi @Jaishree2310, would it be possible for you to add the Hacktoberfest label as well?

**Comment by Jaishree2310** [comment]
@BaraniVA Please resolve the conflicts and read the order of components given in the read me follow that serial-wise.

**Comment by BaraniVA** [comment]
@Jaishree2310 sure sorry for the trouble caused

**Comment by BaraniVA** [comment]
@Jaishree2310 resolved and updated the commits please check and let me know for further changes

https://github.com/user-attachments/assets/de532fe7-9da2-4b82-8128-4a1995ce729a

**Comment by Jaishree2310** [comment]
@BaraniVA Still not resolved

**Pull request closed without merging**
