### PR TITLE
Added terms and conditions

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Jaishree2310 
I have added terms and conditions page
kindly check it out

https://github.com/user-attachments/assets/3a6380c9-b335-49fe-8f01-c47cb586939a

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Could you please consider it as level3

**Comment by Jaishree2310** [comment]
@AswaniBolisetti, Tbh there is no gov terms in the project and other things which are not related to the project please remove.

**Comment by Jaishree2310** [comment]
@AswaniBolisetti try to stick to the theme of glassmorphism How you can design the t&c page with this. Make it interactive other no one will see that

**Comment by AswaniBolisetti** [comment]
> @AswaniBolisetti try to stick to the theme of glassmorphism How you can design the t&c page with this. Make it interactive other no one will see that

I didn't understand, i made it to align with the website styling, I'll remove those things from terms and conditions,

**Comment by Jaishree2310** [comment]
@AswaniBolisetti Please update

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
I'll do it by today evening, I'll remove that gov rule and resolve the conflicts

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Now i removed gov rule and that white space in the footer too
could you please check it now


https://github.com/user-attachments/assets/86884e4f-116f-47e4-979d-9cd44b3c27f7

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 could you please review and merge it please it took so much effort

**Comment by Jaishree2310** [comment]
The conflicts are still present please resolve them, then I will merge.

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 Sure

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Done, kindly check it out now

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Could you please review it

**Comment by Jaishree2310** [comment]
@AswaniBolisetti please resolve the conflicts

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Kindly check now
Solved conflicts

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
Kindly merge it

**Comment by Jaishree2310** [comment]
@AswaniBolisetti Please resolve the conflicts.

**Comment by AswaniBolisetti** [comment]
@Jaishree2310 
check now
and please merge this
I have put so much effort for this

**Pull request closed without merging**
