### PR TITLE
improve ui of searchbar added no result found page

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #204 

Screenshot 2024-10-16 235125

Improved the design of search bar as our website theme

Screenshot 2024-10-16 235320

Also added no result found page for better user experience !!

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah 
Please always check to resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 Resolved conflicts  !!

**Comment by Jaishree2310** [comment]
the deployment is failing

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 but u just change the ui nothing else...!

**Comment by Sawan-Kushwah** [comment]
Can u share logs of deployment so that we can solve it? Or find out the reason why it's falling

**Comment by Sawan-Kushwah** [comment]
@Jaishree2310 i am closing this PR ! as i have done changes in this branch to resolve deployment issue but its creating problem which is not good for our Website so i will do this task in another PR !!

**Pull request closed without merging**
