### PR TITLE
Update README.md added Stargazers and Forkers section to readme.md

### LINKED ISSUE #323: 📝[DOCS] adding Stargazers and Forkers section to readme.md
Current Section
missing Stargazers and Forkers section

Proposed Change
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL2 OR LEVEL3
ASSIGN ME THE WORK
THANK YOU @Jaishree2310

### PR DESCRIPTION
**Pull request by amiya-cyber**
added Stargazers and Forkers section to readme.md

ISSUE #323 
CLOSE #323 

Pull Request

Title
added Stargazers and Forkers section to readme.md

Description
added Stargazers and Forkers section to readme.md which was missing earlier

Changes Made
-Documentation update

Screenshots

### CODE REVIEW

**Comment by amiya-cyber** [comment]
hello @Jaishree2310 if  you can review the pr

**Comment by Jaishree2310** [comment]
@amiya-cyber Please resolve the conflicts.

**Comment by amiya-cyber** [comment]
please @Jaishree2310 review the pr

**Comment by amiya-cyber** [comment]
please @Jaishree2310 review asap

**Comment by amiya-cyber** [comment]
hello @Jaishree2310 please add levels to this pr you have attached all the labels to the issue but you have not give any levels to this pr

**Comment by amiya-cyber** [comment]
and there are two stargazers and forkers section you can remove the white bg section it does not look good according to the theme of your read me

**Pull request merged**
