### PR TITLE
Made a login page with feature of authentication #111

### PR DESCRIPTION
**Pull request by isimarjitsingh**
https://github.com/Jaishree2310/GlassyUI-Components/issues/111

i made a login page with authentication feature so old users start from their where they left.
i made a authentication with the help of firebase which is a google base tool which helps to deal with backend features.

here is the photo of login page

Screenshot 2024-10-13 023459

IF YOU LIKE THIS CONTRIBUTION PLEASE PROMOTE IT TO  "LEVEL 3"  LABEL

### CODE REVIEW

**Comment by isimarjitsingh** [comment]
NOW NO CONFLICTS AT THERE :)

**Comment by Jaishree2310** [comment]
@isimarjitsingh, there are some rules that i need to follow for levels. I believe the design is good but the background is not what a glassmorphism theme looking good. Can you please make it more Better? 
I value your contribution and your work is remarkable indeed!

**Comment by isimarjitsingh** [comment]
Screenshot 2024-10-14 221618
 IS IT CONVINCING

**Comment by isimarjitsingh** [comment]
https://github.com/user-attachments/assets/b3a8b298-7174-495c-884b-e8f3874f7a43

This is video which helps to understand that how my authentication working

**Comment by isimarjitsingh** [comment]
as you see in video user trying to login even he/she doesn't signup before and firebase shows an error and when user completes his/her signup first then he able to login and it futher helps old user to start from their they left

**Comment by Jaishree2310** [comment]
@isimarjitsingh, background still looks very old design kind off login page. 
If you can research more on this thing i am sure you will get the new design idea.

**Comment by isimarjitsingh** [comment]
but my main concern is backend authentication no  the designing

**Pull request closed without merging**
