### PR TITLE
fixed progress bar width in mobile view

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
#82 
Screenshot 2024-10-15 185247

Before merging this PR

image

After merging this PR

### CODE REVIEW

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Please resolve the conflicts.

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah The issue is still present

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/2f1979cf-609b-4234-a861-8970aa2c8ee4
@Jaishree2310 
See it!

**Comment by Hemu21** [comment]
@Jaishree2310 , I am one of the program manager of gssoc-ext. can you please u please update the level label. you have given level 2. but the code is not much change. you can make it level 1.

**Comment by Hemu21** [comment]
@Sawan-Kushwah  i had reviewed yours all prs all are good but only this pr will have level reduce. I saw you doesn't completed the postman challenge. do complete it and create pr in postman repo to get 500 points and lucky winners of postman challenge will get postman swags

**Comment by Sawan-Kushwah** [comment]
@Hemu21 can u share some details of this challenge

**Comment by Hemu21** [comment]
> @Hemu21 can u share some details of this challenge

you can check the postman challenge in the gssoc website. you can get the clear idea. Their the repo for the postman challenge also.

**Pull request merged**
